services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow_server
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow/mlruns.db
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/mlflow/mlartifacts
    volumes:
      - .:/mlflow
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow/mlruns.db
      --default-artifact-root /mlflow/mlartifacts
      --host 0.0.0.0
      --port 5000
    restart: unless-stopped 